# Generated by Django 4.2.7 on 2023-12-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
