# Generated by Django 4.2.7 on 2023-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_category'),
        ('tasks', '0002_remove_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
